# This rule is not used by the project serviceaccount-quota itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to quota.mayooot.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount-quota
    app.kubernetes.io/managed-by: kustomize
  name: serviceaccountquota-viewer-role
rules:
- apiGroups:
  - quota.mayooot.github.io
  resources:
  - serviceaccountquotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quota.mayooot.github.io
  resources:
  - serviceaccountquotas/status
  verbs:
  - get
